### ISSUE TITLE
Также нужно завернуть все инпуты в тег "form"

### ISSUE THREAD

**Issue by dmitrolov** [Oksana-ua2020/Exam-CSS#3]
https://github.com/Oksana-ua2020/Exam-CSS/blob/7135876e9068da4b44decf558ea478e600f98dbc/index.html#L29

**Comment by Oksana-ua2020** [comment]
<form class="sect-main">
            <div class="container">
                <aside class="aside">
                    <div class="search">
                        <p class="p-input-h"> <b>Name</b><br>
